# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_DB: <your_db_name> #encoded in Base64
  POSTGRES_USER: <your_db_user> #encoded in Base64
  POSTGRES_PASSWORD: <your_db_password> #encoded in Base64
