# Generated by Django 5.1.2 on 2024-10-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ISSData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_latitude", models.FloatField()),
                ("user_longitude", models.FloatField()),
                ("iss_latitude", models.FloatField()),
                ("iss_longitude", models.FloatField()),
                ("azimuth", models.FloatField()),
                ("elevation", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
