# Generated by Django 5.1.2 on 2024-10-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issdata",
            name="iss_speed",
            field=models.FloatField(null=True),
        ),
    ]
